//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CodeMate.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CODEMATE_MAIN               102
#define IDS_INDICATOR_MESSAGE           102
#define IDC_POINTER                     104
#define IDR_MAINFRAME                   128
#define IDR_MENU_RBUTTON                129
#define IDB_BITMAP1                     129
#define IDS_INDICATOR_TIME              130
#define IDB_BITMAP2                     130
#define IDS_SPRITTER_MOVING             131
#define IDB_BITMAP3                     131
#define IDS_SPRITTER_EAGE               132
#define IDD_ADDITEM_DIALOG              132
#define IDB_BITMAP4                     132
#define IDS_LINE_INFO                   133
#define IDD_DIALOG_GOTO                 133
#define IDS_MSGBOX_INFO                 134
#define IDB_BITMAP5                     133
#define IDB_BITMAP6                     134
#define IDB_BITMAP7                     135
#define IDS_MSGBOX_WARN                 135
#define IDD_DIALOG_CONFIG               135
#define IDB_BITMAP8                     136
#define IDS_MSGBOX_ERROR                136
#define IDS_MSGBOX_QUES                 137
#define IDD_MOVETO_DIALOG               137
#define IDB_BITMAP9                     137
#define IDS_MSGBOX_ADDITEM              138
#define IDS_MSGBOX_SAVEERROR            138
#define IDB_BITMAP10                    138
#define IDS_MSGBOX_ADDCLASS             139
#define IDS_MSGBOX_FILEEXIST            139
#define IDB_BITMAP11                    139
#define IDS_MSGBOX_MOVEITEM             140
#define IDB_BITMAP12                    140
#define IDS_MSGBOX_DELITEM              141
#define IDB_BITMAP13                    141
#define IDS_MSGBOX_CLEARCLASS           142
#define IDB_BITMAP14                    142
#define IDS_CLASS_NORMAL                143
#define IDB_BITMAP15                    143
#define IDB_BITMAP16                    144
#define IDS_ITEM_SHOW                   144
#define IDB_BITMAP17                    145
#define IDS_MSGBOX_NOTEMPTY             145
#define IDS_MSGBOX_NONECLASS            146
#define IDS_MSGBOX_DELERROR             146
#define IDB_BITMAP18                    146
#define IDB_SPLITTER                    147
#define IDS_MSGBOX_INCLASS              147
#define IDC_CURSOR_SPLITTER             148
#define IDS_MSGBOX_EXPSUC               148
#define IDS_MSGBOX_NAMEERROR            149
#define ID_INDICATOR_LANG               150
#define IDB_TOOLBAR_DISABLE             150
#define IDS_DLG_ADDITEM1                151
#define IDS_MSGBOX_RENAMEERR            151
#define IDS_DLG_ADDITEM2                152
#define IDS_MSGBOX_PATHERR              152
#define IDS_DLG_ADDITEM3                153
#define IDS_PREP_NOTACCES               153
#define IDS_DLG_ADDITEM4                154
#define IDS_MSGBOX_MOVEERR              154
#define IDS_NEW_CLASS                   155
#define IDS_MSGBOX_ADDCLASS_ERR         156
#define IDS_MNU_DELCLASS                157
#define IDS_MNU_DELITEM                 158
#define IDD_CHANGELANG_DIALOG           158
#define IDS_MNU_RENAMECLASS             159
#define IDS_MNU_RENAMEITEM              160
#define IDS_MSGBOX_LOADERROR            161
#define IDD_DIALOG_PREP                 161
#define IDS_MSGBOX_EXITWARN             162
#define IDS_MSGBOX_DELCLASS             163
#define IDS_MSGBOX_MOVETOERR            164
#define IDS_MSGBOX_PATHNOTEXIST         165
#define IDS_INDICATOR_FILE              166
#define IDS_INDICATOR_FOCUS             167
#define IDS_ABOUT_VERSION_E             168
#define IDS_ABOUT_DES_E                 169
#define IDS_ABOUT_CR_E                  170
#define IDS_ABOUT_DES_T                 171
#define IDS_ATTRIB_CLASS                172
#define IDS_ABOUT_CR_T                  173
#define IDS_ABOUT_TITLE_E               174
#define IDS_ABOUT_TITLE_T               175
#define IDS_ATTRIB_ITEM                 176
#define IDS_DEFAULT_COLOR               177
#define IDS_MORE_COLOR                  178
#define IDS_FONT_BOLD                   179
#define IDS_FONT_ITALIC                 180
#define IDS_TAB_APPEARANCE              181
#define IDS_TAB_EDITOR                  182
#define IDS_MSGBOX_PATHCHANGE           183
#define IDS_MSGBOX_PATH_INVILID         184
#define IDS_SEARCH_CONTENT              185
#define IDS_SEARCH_BUTTON               186
#define IDS_SEARCH_CHECK                187
#define IDS_SEARCH_HIDE                 188
#define IDS_COMBO_ALL                   189
#define IDS_COMBO_CLASS                 190
#define IDS_MSGBOX_PL_INPUT             191
#define IDS_ABOUT_OPENSOURCE_E          192
#define IDS_ABOUT_OPENSOURCE_T          193
#define IDC_TREE1                       1000
#define IDC_STATIC_VERSION              1000
#define IDC_EDIT_CLASS                  1001
#define IDC_COMBO1                      1002
#define IDC_STATIC_DES                  1002
#define IDC_RADIO1                      1003
#define IDC_STATIC_CR                   1003
#define IDC_RADIO2                      1004
#define IDC_STATIC_CR2                  1004
#define IDC_STATIC_OPEN                 1004
#define IDC_STATIC_TITLE                1005
#define IDC_STATIC_CLASS                1006
#define IDC_CHANGE_CLASS                1007
#define IDC_EDIT_TITLE                  1008
#define IDC_STATIC_LANG                 1009
#define IDC_STATIC_SOURCE               1010
#define IDC_STATIC_NAME                 1011
#define IDC_STATIC_TEXT                 1011
#define IDC_RADIO3                      1012
#define IDC_STATIC_INPUT                1012
#define IDC_BUTTON_SPLITTER             1013
#define IDC_STATIC_LANTYPE              1013
#define IDC_STATIC_CTIME                1014
#define IDC_STATIC_MTIME                1015
#define IDC_STATIC_ATIME                1016
#define IDC_BUTTON2                     1017
#define IDC_SET_DEFAULT                 1017
#define IDC_BUTTON_HIDE                 1017
#define IDC_COMBO_LANG                  1018
#define IDC_LIST1                       1020
#define IDC_EDIT1                       1022
#define IDC_EDIT2                       1023
#define IDC_STATIC_TYPE                 1024
#define IDC_STATIC_CRETIME              1025
#define IDC_STATIC_MODTIME              1026
#define IDC_STATIC_ACCTIME2             1027
#define IDC_STATIC_ACCTIME              1027
#define IDC_SPIN1                       1027
#define IDC_STATIC_LINE_NO              1028
#define IDC_EDIT_LINE                   1029
#define IDC_STATIC_COLUMN_NO            1030
#define IDC_SPIN2                       1031
#define IDC_EDIT_COLUMN                 1032
#define IDC_MFCCOLORBUTTON1             1035
#define IDC_MFCCOLORBUTTON2             1036
#define IDC_MFCCOLORBUTTON3             1037
#define IDC_MFCFONTCOMBO1               1038
#define IDC_MFCCOLORBUTTON5             1038
#define IDC_MFCPROPERTYGRID1            1039
#define IDC_MFCCOLORBUTTON4             1039
#define IDC_MFCCOLORBUTTON6             1040
#define IDC_STATIC_FONT                 1041
#define IDC_STATIC_COLOR1               1042
#define IDC_STATIC_COLOR2               1043
#define IDC_STATIC_EDITOR               1044
#define IDC_STATIC_COLOR3               1045
#define IDC_STATIC_COLOR4               1046
#define IDC_STATIC_COLOR7               1047
#define IDC_STATIC_COLOR5               1048
#define IDC_BUTTON1                     1049
#define IDC_STATIC_COLOR6               1050
#define IDC_STATIC_FONT_SET             1051
#define IDC_STATIC_COLOR8               1051
#define IDC_STATIC_MAIN                 1052
#define IDC_STATIC_IMG                  1053
#define IDC_TAB1                        1054
#define IDC_STATIC_GENERALS             1055
#define IDC_CHECK1                      1056
#define IDC_STATIC_TABS                 1057
#define IDC_STATIC_POSITION             1059
#define IDC_MFCVSLISTBOX1               1061
#define IDC_MFCVSLISTBOX2               1062
#define IDC_MFCPROPERTYGRID2            1063
#define IDC_STATIC_ADD                  1064
#define IDC_STATIC_LAN                  1065
#define IDC_STATIC_ENCODING             1066
#define IDC_SPLIT2                      1069
#define IDC_STATIC_SEARCH               1070
#define IDC_BUTTON_SEARCH               1072
#define IDS_AFXBARRES_NEW               16017
#define IDS_AFXBARRES_DELETE            16020
#define IDS_AFXBARRES_MOVEUP            16021
#define IDS_AFXBARRES_MOVEDN            16022
#define IDC_AFXBARRES_COLOR             16145
#define IDC_AFXBARRES_COLOURPLACEHOLDER 16662
#define IDD_AFXBARRES_COLOR_DLG         16961
#define IDD_AFXBARRES_COLOR_PAGE_ONE    16962
#define IDD_AFXBARRES_COLORPAGE_TWO     16963
#define IDC_AFXBARRES_R                 16964
#define IDC_AFXBARRES_G                 16965
#define IDC_AFXBARRES_B                 16966
#define IDC_AFXBARRES_L                 16967
#define IDC_AFXBARRES_S                 16968
#define IDC_AFXBARRES_H                 16969
#define IDC_AFXBARRES_STATICPLACEHOLDER 16970
#define IDC_AFXBARRES_GREYSCALEPLACEHOLDER 16972
#define IDC_AFXBARRES_LUMINANCEPLACEHOLDER 16973
#define IDC_AFXBARRES_HEXPLACEHOLDER    16974
#define IDC_AFXBARRES_SPIN1             16976
#define IDC_AFXBARRES_SPIN2             16977
#define IDC_AFXBARRES_SPIN3             16978
#define IDC_AFXBARRES_SPIN4             16979
#define IDC_AFXBARRES_SPIN5             16980
#define IDC_AFXBARRES_SPIN6             16981
#define IDC_AFXBARRES_COLOR_SELECT      17045
#define IDB_AFXBARRES_COLOR_PICKER      17046
#define IDB_AFXBARRES_BROWSE32          17049
#define IDB_AFXBARRES_NEW32             17053
#define IDB_AFXBARRES_DELETE32          17054
#define IDB_AFXBARRES_UP32              17055
#define IDB_AFXBARRES_DOWN32            17057
#define ID_Menu                         32771
#define ID_FILE_DELITEM                 32774
#define ID_EDIT_SHOWLIST                32777
#define ID_EDIT_GOTO                    32780
#define ID_DELETE_ITEM                  32782
#define ID_CLEAR_CLASS                  32784
#define ID_RENAME_ITEM                  32785
#define ID_A_LINE                       32787
#define ID_DEL_A_LINE                   32788
#define ID_Menu32789                    32789
#define ID_EDIT_FIND_NEXT               32791
#define ID_FILE_SEARCH                  32797
#define ID_EDIT_DELETE                  32804
#define ID_EDIT_SELALL                  32805
#define ID_LAN_CHNS                     32811
#define ID_LAN_CHNT                     32812
#define ID_LAN_ENG                      32813
#define ID_FILE_ADDITEM                 32815
#define ID_FILE_ADDCLASS                32816
#define ID_FILE_MOVETO                  32818
#define ID_SET_OPTION                   32820
#define ID_FILE_RELOAD                  32849
#define ID_EDIT_CHANGE_TYPE             32851
#define IDS_ABOUT_VERSION               32852
#define ID_FILE_PREP                    32853
#define ID_SKIN                         32860
#define IDS_NORMAL_TEXT                 57605

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
